-- Criar tabela de Receitas Manuais
CREATE TABLE IF NOT EXISTS public.receitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL DEFAULT 'Outros',
    veiculo_placa TEXT,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    valor DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'Em aberto',
    parcelamento_id TEXT, -- Para agrupar parcelas
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    user_id UUID DEFAULT auth.uid()
);

-- Habilitar RLS
ALTER TABLE public.receitas ENABLE ROW LEVEL SECURITY;

-- Criar políticas de acesso
CREATE POLICY "Usuários podem ver suas próprias receitas"
ON public.receitas FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem criar suas próprias receitas"
ON public.receitas FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Usuários podem atualizar suas próprias receitas"
ON public.receitas FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Usuários podem deletar suas próprias receitas"
ON public.receitas FOR DELETE
USING (auth.uid() = user_id);
