-- Correções críticas de privilégio e trilha de auditoria.
BEGIN;

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT;
UPDATE public.profiles SET role = 'operacao' WHERE role IS NULL OR role NOT IN ('admin', 'gerente', 'operacao');
ALTER TABLE public.profiles ALTER COLUMN role SET DEFAULT 'operacao';
ALTER TABLE public.profiles ALTER COLUMN role SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_role_check') THEN
        ALTER TABLE public.profiles
        ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'gerente', 'operacao')) NOT VALID;
        ALTER TABLE public.profiles VALIDATE CONSTRAINT profiles_role_check;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT role FROM public.profiles WHERE id = auth.uid()
$$;
REVOKE ALL ON FUNCTION public.get_user_role() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_role() TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nome, role)
    VALUES (
        NEW.id,
        NEW.email,
        NEW.raw_user_meta_data ->> 'nome',
        'operacao'
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        nome = COALESCE(EXCLUDED.nome, public.profiles.nome);

    INSERT INTO public.categorias_financeiras (user_id, codigo, nome, natureza, grupo_dre)
    VALUES
        (NEW.id, 'locacao', 'Receita de locação', 'receita', 'receita_operacional'),
        (NEW.id, 'receita_nao_classificada', 'Receita não classificada', 'receita', 'receita_operacional'),
        (NEW.id, 'venda_ativo', 'Venda de veículo', 'receita', 'resultado_nao_operacional'),
        (NEW.id, 'manutencao', 'Manutenção', 'despesa', 'custos_servicos'),
        (NEW.id, 'seguro', 'Seguro', 'despesa', 'custos_servicos'),
        (NEW.id, 'principal_financiamento', 'Principal de financiamento', 'despesa', 'fluxo_financiamento'),
        (NEW.id, 'juros_encargos', 'Juros e encargos', 'despesa', 'resultado_financeiro'),
        (NEW.id, 'tributos_receita', 'Tributos sobre receita', 'deducao', 'deducoes_receita'),
        (NEW.id, 'nao_classificada', 'Não classificada', 'despesa', 'despesas_operacionais')
    ON CONFLICT (user_id, codigo) DO NOTHING;

    INSERT INTO public.configuracoes (user_id)
    VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
REVOKE INSERT, DELETE ON public.profiles FROM authenticated;

CREATE OR REPLACE FUNCTION public.prevent_unauthorized_role_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF NEW.role IS DISTINCT FROM OLD.role
       AND NOT EXISTS (
           SELECT 1 FROM public.profiles
           WHERE id = auth.uid() AND role = 'admin'
       )
    THEN
        RAISE EXCEPTION 'Alteração de perfil não autorizada';
    END IF;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.prevent_unauthorized_role_change() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS prevent_unauthorized_role_change ON public.profiles;
CREATE TRIGGER prevent_unauthorized_role_change
BEFORE UPDATE OF role ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.prevent_unauthorized_role_change();

CREATE OR REPLACE FUNCTION public.set_profile_role(target_user UUID, new_role TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    IF public.get_user_role() <> 'admin' THEN RAISE EXCEPTION 'Acesso negado'; END IF;
    IF new_role NOT IN ('admin', 'gerente', 'operacao') THEN RAISE EXCEPTION 'Perfil inválido'; END IF;
    IF new_role <> 'admin'
       AND (SELECT role FROM public.profiles WHERE id = target_user) = 'admin'
       AND (SELECT COUNT(*) FROM public.profiles WHERE role = 'admin') <= 1
    THEN
        RAISE EXCEPTION 'O último administrador não pode ser rebaixado';
    END IF;
    UPDATE public.profiles SET role = new_role WHERE id = target_user;
    IF NOT FOUND THEN RAISE EXCEPTION 'Usuário não encontrado'; END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.set_profile_role(UUID, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_profile_role(UUID, TEXT) TO authenticated;

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    user_id UUID,
    user_role TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.audit_logs
    ADD COLUMN IF NOT EXISTS schema_name TEXT,
    ADD COLUMN IF NOT EXISTS txid BIGINT,
    ADD COLUMN IF NOT EXISTS request_id TEXT;

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.audit_logs FROM anon, authenticated;
GRANT SELECT ON public.audit_logs TO authenticated;
DROP POLICY IF EXISTS "Admins ver logs" ON public.audit_logs;
CREATE POLICY "Admins ver logs" ON public.audit_logs
FOR SELECT USING (public.get_user_role() = 'admin');

CREATE OR REPLACE FUNCTION public.log_audit_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    row_data JSONB;
    record_key TEXT;
    actor_role TEXT;
    request_headers JSONB;
BEGIN
    row_data := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
    record_key := COALESCE(row_data ->> 'id', 'sem-id');
    SELECT role INTO actor_role FROM public.profiles WHERE id = auth.uid();
    BEGIN
        request_headers := NULLIF(current_setting('request.headers', TRUE), '')::jsonb;
    EXCEPTION WHEN OTHERS THEN
        request_headers := NULL;
    END;

    INSERT INTO public.audit_logs (
        schema_name, table_name, record_id, operation, old_data, new_data,
        user_id, user_role, txid, request_id, changed_at
    ) VALUES (
        TG_TABLE_SCHEMA, TG_TABLE_NAME, record_key, TG_OP,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END,
        auth.uid(), COALESCE(actor_role, 'operacao'), txid_current(),
        request_headers ->> 'x-request-id',
        NOW()
    );
    RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public.log_audit_event() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'veiculos', 'motoristas', 'contratos', 'pagamentos', 'receitas',
        'despesas', 'manutencoes', 'multas', 'sinistros', 'categorias_financeiras', 'profiles'
    ]
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS audit_%I ON public.%I', table_name, table_name);
        EXECUTE format(
            'CREATE TRIGGER audit_%I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.log_audit_event()',
            table_name, table_name
        );
    END LOOP;
END;
$$;

-- O cliente público é usado apenas para autenticação; dados exigem sessão.
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon;

-- Funções legadas: restringe execução e impede resolução de objetos controlada
-- pelo chamador. A função de criação de políticas é somente administrativa.
ALTER FUNCTION public.create_user_policies(TEXT) SET search_path = 'public';
REVOKE ALL ON FUNCTION public.create_user_policies(TEXT) FROM PUBLIC, anon, authenticated;
ALTER FUNCTION public.update_updated_at_column() SET search_path = '';

REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.registrar_venda_veiculo(INTEGER, NUMERIC, DATE, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_profile_role(UUID, TEXT) TO authenticated;

COMMIT;
